### ISSUE TITLE
Allow truncated site name with full name on hover

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/dashboard-charts#13]
# Test notes
* Verify that values of the _category_abbreviation_ column in the data plot on the y-axis instead of values in the _category_ column.
* Verify that specifying a nonexistent column for _Category Abbreviation_ results in the _category_ column plotting on the y-axis.

**Comment by rchronowic** [comment]
Verified that category_abbreviation plots to the values on y-axis, but when removing values for category_abbreviation the y-axis was left blank instead of pulling from category.

**Comment by samussiah** [comment]
Ditto here @rchronowic , try changing the data mapping in CAT rather than the values in the data:

![image](https://user-images.githubusercontent.com/5428548/63355988-0b31b200-c335-11e9-8e72-2ce964ca9887.png)

**Comment by rchronowic** [comment]
Tested and passed in CAT.
