### ISSUE TITLE
Enforce standard x-axis regardless of subset

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/dashboard-charts#18]
The user specified "Always start at the same date even if the site hasn't started enrolling at that beginning date".

# Test notes
* Verify changing the filter does not change the range of the x-axis.

**Comment by emmorris** [comment]
This was already in place before.  The user requested it, but we confirmed that it is already in place.  No code changes.  We never tested it previously though, so we should still do that.

**Comment by rchronowic** [comment]
Tested and passed in CAT.
