### ISSUE TITLE
Support overall target and site target

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/dashboard-charts#19]
Use site activation date and expected enrollment.

**Comment by pburnsdata** [comment]
Not totally sure on this one - I added "total target" and "site target" rows so that either could be used

**Comment by emmorris** [comment]
@pburnsdata and @samussiah , not sure if this helps, but there was a note about this one stating that Spencer would figure out what is easiest on our side.  The note said that we would figure out if it would be better to leave site blank if they want overall target.

**Comment by samussiah** [comment]
We currently support site/filter-level targets.  Need to add a new data file for overall target disregarding any sub-population (site, cohrot, etc.).

**Comment by emmorris** [comment]
Two data files.  One with site target and one with overall.  @pburnsdata to create the datasets.

**Comment by samussiah** [comment]
The chart renderer handles site-level and study-level without any modifications to the codebase.

**Comment by rchronowic** [comment]
Passed testing in CAT.
