### ISSUE TITLE
Allow for substitutions

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/dashboard-charts#20]
If needed, allow for different filter or replace site column with cohort column.

**Comment by samussiah** [comment]
Filter columns are now supported but site cannot be replaced with cohort, at least in the accrual bar chart.

**Comment by samussiah** [comment]
I can think of a couple routes:

- Generalize the settings by replacing anything referencing _site_ with _categorical_ or _discrete_ but still defaulting to _site_.  Only issue here is that customizations to the chart layout would not be data-driven but settings-driven.
- In addition to generalizing the settings, generalize variable names in the input data:
  - _site_ to _category_
  - _site_abbreviation_ to _category_abbreviation_
  - _site_info_ to _category_info_

**Comment by rchronowic** [comment]
Tested and passed in CAT. Note: When changing values in column e.g. Site 01 to Duke, must change the value in both the category_abbreviation (in Chart - Site 01) and filter:Site (to change value in drop down).
