### ISSUE TITLE
Ensure that optional variables are truly optional.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/dashboard-charts#31]
# Test notes
* For optional data mappings, settings without an asterisk in the form view of the settings in CAT, verify that specifying a nonexistent variable does not result in an error or in the chart not rendering.

**Comment by emmorris** [comment]
@samussiah , does this apply to both the bar chart and the enrollment over time chart?

**Comment by samussiah** [comment]
@emmorris , yes, both charts have optional data mappings and I noticed an error in the dashboard framework when removing optional data mappings.
